name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  npm_dedupe_check:
    name: NPM dependency duplication check
    uses: vazco/open-standards/.github/workflows/check_dependency_duplications.yml@master
  npm_vuln_check:
    name: NPM dependency vulnerabilities check
    uses: vazco/open-standards/.github/workflows/check_dependency_vulnerabilities.yml@master
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.2.0
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm i -g npm@7 && npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run coverage -- --no-cache --runInBand
      - name: Report coverage
        uses: codecov/codecov-action@v2.1.0
        with:
          fail_ci_if_error: true
          verbose: true
      - name: Build docs
        run: npm --prefix website run build
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.node-version == '16.x'
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          allow_empty_commit: true
          cname: uniforms.tools
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.node-version == '16.x'
